name: Extract Text from Documents

on:
  workflow_dispatch: # Allows manual triggering
  push:
    paths:
      - 'docs/**.pdf'
      - 'docs/**.docx'
      - 'websites/**.html'

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pdfplumber python-docx beautifulsoup4 requests

    - name: Extract text from documents
      run: |
        python extract_text.py
